
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author hdann
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        Modificar = new javax.swing.JMenuItem();
        Eliminar = new javax.swing.JMenuItem();
        dialogPersonal = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        id_personal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombre_personal = new javax.swing.JTextField();
        edad_personal = new javax.swing.JSpinner();
        sexo_personal = new javax.swing.JComboBox<>();
        estado_personal = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        altura_personal = new javax.swing.JTextField();
        peso_personal = new javax.swing.JTextField();
        ocupacion_personal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        horario_personal = new javax.swing.JTextField();
        tiempo_personal = new javax.swing.JTextField();
        sueldo_personal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        dialogGerente = new javax.swing.JDialog();
        dialogObjeto = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        botonPersonal = new javax.swing.JButton();
        botonGerente = new javax.swing.JButton();
        botonObjeto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTreePersonal = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTreeObjeto = new javax.swing.JTree();

        Modificar.setText("jMenuItem1");
        jPopupMenu1.add(Modificar);

        Eliminar.setText("jMenuItem1");
        jPopupMenu1.add(Eliminar);

        dialogPersonal.setBackground(new java.awt.Color(255, 255, 255));
        dialogPersonal.setMaximumSize(new java.awt.Dimension(580, 450));
        dialogPersonal.setModal(true);
        dialogPersonal.setPreferredSize(new java.awt.Dimension(580, 450));
        dialogPersonal.setSize(new java.awt.Dimension(580, 450));
        dialogPersonal.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ID");
        dialogPersonal.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 37, -1));
        dialogPersonal.getContentPane().add(id_personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 119, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre");
        dialogPersonal.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 54, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Edad");
        dialogPersonal.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 54, -1));
        dialogPersonal.getContentPane().add(nombre_personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 119, -1));
        dialogPersonal.getContentPane().add(edad_personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 119, -1));

        sexo_personal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        dialogPersonal.getContentPane().add(sexo_personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 119, -1));

        estado_personal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltero", "Casado", "Divorciado", "Viudo" }));
        dialogPersonal.getContentPane().add(estado_personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 119, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Estado");
        dialogPersonal.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 54, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Sexo");
        dialogPersonal.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 54, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Altura");
        dialogPersonal.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 54, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Peso");
        dialogPersonal.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 54, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Ocupacion");
        dialogPersonal.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));
        dialogPersonal.getContentPane().add(altura_personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 119, -1));
        dialogPersonal.getContentPane().add(peso_personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 119, -1));
        dialogPersonal.getContentPane().add(ocupacion_personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 119, -1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Horario");
        dialogPersonal.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Tiempo");
        dialogPersonal.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Sueldo");
        dialogPersonal.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));
        dialogPersonal.getContentPane().add(horario_personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 119, -1));
        dialogPersonal.getContentPane().add(tiempo_personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 119, -1));
        dialogPersonal.getContentPane().add(sueldo_personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 119, -1));

        jButton1.setText("Agregar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        dialogPersonal.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 141, 55));

        dialogGerente.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout dialogGerenteLayout = new javax.swing.GroupLayout(dialogGerente.getContentPane());
        dialogGerente.getContentPane().setLayout(dialogGerenteLayout);
        dialogGerenteLayout.setHorizontalGroup(
            dialogGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 693, Short.MAX_VALUE)
        );
        dialogGerenteLayout.setVerticalGroup(
            dialogGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout dialogObjetoLayout = new javax.swing.GroupLayout(dialogObjeto.getContentPane());
        dialogObjeto.getContentPane().setLayout(dialogObjetoLayout);
        dialogObjetoLayout.setHorizontalGroup(
            dialogObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dialogObjetoLayout.setVerticalGroup(
            dialogObjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        botonPersonal.setText("Personal");
        botonPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonPersonalMouseClicked(evt);
            }
        });

        botonGerente.setText("Gerente");
        botonGerente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGerenteMouseClicked(evt);
            }
        });

        botonObjeto.setText("Objeto");
        botonObjeto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonObjetoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonObjeto, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(botonGerente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(botonPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(botonGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(botonObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Personal");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Gerente");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode(".");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Personal");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode(".");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTreePersonal.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTreePersonal);

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jTreeObjeto.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane2.setViewportView(jTreeObjeto);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 173, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPersonalMouseClicked
        dialogPersonal.pack();
        dialogPersonal.setModal(true);
        dialogPersonal.setLocationRelativeTo(this);
        dialogPersonal.setVisible(true);
    }//GEN-LAST:event_botonPersonalMouseClicked

    private void botonGerenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGerenteMouseClicked
        dialogGerente.pack();
        dialogGerente.setModal(true);
        dialogGerente.setLocationRelativeTo(this);
        dialogGerente.setVisible(true);
    }//GEN-LAST:event_botonGerenteMouseClicked

    private void botonObjetoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonObjetoMouseClicked
        dialogObjeto.pack();
        dialogObjeto.setModal(true);        
        dialogObjeto.setLocationRelativeTo(this);
        dialogObjeto.setVisible(true);
    }//GEN-LAST:event_botonObjetoMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        DefaultTreeModel modelo = (DefaultTreeModel) jTreePersonal.getModel();
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) modelo.getRoot();

        General emp = new General();
        emp.setId(Integer.parseInt(id_personal.getText()));
        emp.setNombre(nombre_personal.getText());
        emp.setEdad((Integer) edad_personal.getValue());
        emp.setSexo((String) sexo_personal.getSelectedItem());
        emp.setEstado((String) estado_personal.getSelectedItem());
        emp.setAltura(Integer.parseInt(altura_personal.getText()));
        emp.setPeso(Integer.parseInt(peso_personal.getText()));
        emp.setOcup(ocupacion_personal.getText());
        emp.setHorario(horario_personal.getText());
        emp.setTiempo(Integer.parseInt(tiempo_personal.getText()));
        emp.setSueldo(Double.parseDouble(sueldo_personal.getText()));
        DefaultMutableTreeNode personal = new DefaultMutableTreeNode(emp);
        ((DefaultMutableTreeNode)root.getChildAt(1)).add(personal);
        
        modelo.reload();
        jTreePersonal.setModel(modelo);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JMenuItem Modificar;
    private javax.swing.JTextField altura_personal;
    private javax.swing.JButton botonGerente;
    private javax.swing.JButton botonObjeto;
    private javax.swing.JButton botonPersonal;
    private javax.swing.JDialog dialogGerente;
    private javax.swing.JDialog dialogObjeto;
    private javax.swing.JDialog dialogPersonal;
    private javax.swing.JSpinner edad_personal;
    private javax.swing.JComboBox<String> estado_personal;
    private javax.swing.JTextField horario_personal;
    private javax.swing.JTextField id_personal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTreeObjeto;
    private javax.swing.JTree jTreePersonal;
    private javax.swing.JTextField nombre_personal;
    private javax.swing.JTextField ocupacion_personal;
    private javax.swing.JTextField peso_personal;
    private javax.swing.JComboBox<String> sexo_personal;
    private javax.swing.JTextField sueldo_personal;
    private javax.swing.JTextField tiempo_personal;
    // End of variables declaration//GEN-END:variables
}
